name: Lint (containerized & hardened)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHP Coding Standards (container)
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    # ✅ Containerized: PHP already available; no APT
    container: php:${{ matrix.php }}-cli
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2']
    steps:
      # ----- Checkout (pin to SHA) -----
      - name: Checkout merge ref
        id: co_merge
        continue-on-error: true
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          fetch-depth: 1
          persist-credentials: false
          path: pr

      - name: Fallback to head ref
        if: steps.co_merge.outcome == 'failure'
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          fetch-depth: 1
          persist-credentials: false
          path: pr

      # ----- Caching: Composer (project + global) -----
      - name: Cache Composer (deps + global)
        uses:  actions/checkout@v5
        with:
          path: |
            ~/.cache/composer
            ~/.composer
            pr/vendor
          # include PHP version in key to avoid cross-version issues
          key: composer-${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('pr/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-php${{ matrix.php }}-
            composer-${{ runner.os }}-

      # ----- Composer (verified installer; no plugins/scripts) -----
      - name: Install Composer (verified)
        shell: bash
        run: |
          set -euo pipefail
          curl --fail --show-error --location --proto '=https' --tlsv1.2 https://composer.github.io/installer.sig -o sig
          curl --fail --show-error --location --proto '=https' --tlsv1.2 https://getcomposer.org/installer -o composer-setup.php
          ACTUAL="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
          EXPECTED="$(cat sig)"
          [ "$EXPECTED" = "$ACTUAL" ] || { echo 'Invalid Composer installer signature' >&2; exit 1; }
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer --quiet
          rm -f composer-setup.php sig
          composer --version

      - name: Install project PHP deps (no scripts)
        working-directory: pr
        shell: bash
        run: |
          set -euo pipefail
          if [ -f composer.json ]; then
            COMPOSER_ALLOW_SUPERUSER=1 composer install \
              --no-interaction --no-progress --prefer-dist \
              --no-scripts --no-plugins || true
          fi

      # ----- PHPCS: use repo ruleset if present; else CI bootstrap -----
      - name: Run PHPCS (use repo phpcs.xml if present)
        id: phpcs_repo
        working-directory: pr
        shell: bash
        run: |
          set -euo pipefail
          if [ -x vendor/bin/phpcs ] && [ -f phpcs.xml ]; then
            echo "Using repository phpcs.xml with vendor/bin/phpcs"
            vendor/bin/phpcs -q
            echo "used_repo=true" >> "$GITHUB_OUTPUT"
          else
            echo "used_repo=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Fetch WordPressCS & companions (CI-only)
        if: steps.phpcs_repo.outputs.used_repo == 'false'
        shell: bash
        run: |
          set -euo pipefail
          git clone --depth 1 --filter=blob:none https://github.com/WordPress/WordPress-Coding-Standards.git /tmp/wpcs
          git clone --depth 1 --filter=blob:none https://github.com/PHPCSStandards/PHPCSUtils.git          /tmp/phpcsutils
          git clone --depth 1 --filter=blob:none https://github.com/PHPCSStandards/PHPCSExtra.git          /tmp/phpcsextra
          # Optional companions (safe if absent)
          git clone --depth 1 --filter=blob:none https://github.com/PHPCompatibility/PHPCompatibility.git   /tmp/phpcompat || true
          git clone --depth 1 --filter=blob:none https://github.com/PHPCompatibility/PHPCompatibilityWP.git /tmp/phpcompatwp || true

      - name: Cache PHPCS standards
        if: steps.phpcs_repo.outputs.used_repo == 'false'
        uses:  actions/checkout@v5
        with:
          path: |
            /tmp/wpcs
            /tmp/phpcsutils
            /tmp/phpcsextra
            /tmp/phpcompat
            /tmp/phpcompatwp
          key: phpcs-standards-${{ runner.os }}-v1

      - name: Ensure PHPCS binary (project or global)
        if: steps.phpcs_repo.outputs.used_repo == 'false'
        id: phpcsbin
        working-directory: pr
        shell: bash
        run: |
          set -euo pipefail
          if [ -x vendor/bin/phpcs ]; then
            echo "bin=vendor/bin/phpcs" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          COMPOSER_ALLOW_SUPERUSER=1 composer global require --no-interaction --no-progress --no-plugins --no-scripts squizlabs/php_codesniffer:^3.10
          PHPCS_BIN="$(composer global config bin-dir --absolute)/phpcs"
          [ -x "$PHPCS_BIN" ] || { echo "Failed to install global PHPCS" >&2; exit 1; }
          echo "bin=$PHPCS_BIN" >> "$GITHUB_OUTPUT"

      - name: Configure PHPCS installed_paths (CI-only)
        if: steps.phpcs_repo.outputs.used_repo == 'false'
        working-directory: pr
        shell: bash
        env:
          BIN: ${{ steps.phpcsbin.outputs.bin }}
        run: |
          set -euo pipefail
          "$BIN" --config-set installed_paths /tmp/wpcs,/tmp/phpcsextra,/tmp/phpcsutils,/tmp/phpcompat,/tmp/phpcompatwp
          echo "PHPCS standards available:"
          "$BIN" -i

      - name: Run PHPCS (WordPress standard) on tracked PHP files
        if: steps.phpcs_repo.outputs.used_repo == 'false'
        working-directory: pr
        shell: bash
        env:
          BIN: ${{ steps.phpcsbin.outputs.bin }}
        run: |
          set -euo pipefail
          files="$(git ls-files '*.php' || true)"
          if [ -z "$files" ]; then
            echo "No PHP files found."
            exit 0
          fi
          printf '%s\n' $files | xargs -n50 "$BIN" -q --standard=WordPress

  eslint:
    name: JavaScript ESLint (container)
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    # ✅ Containerized: Node already available; no NVM
    container: node:${{ matrix.node }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node: ['18', '20']
    steps:
      - name: Checkout merge ref
        id: co_merge
        continue-on-error: true
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          fetch-depth: 1
          persist-credentials: false
          path: pr

      - name: Fallback to head ref
        if: steps.co_merge.outcome == 'failure'
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          fetch-depth: 1
          persist-credentials: false
          path: pr

      - name: Detect package.json
        id: pkg
        working-directory: pr
        shell: bash
        run: |
          set -euo pipefail
          if [ -f package.json ]; then echo "found=true" >> "$GITHUB_OUTPUT"; else echo "found=false" >> "$GITHUB_OUTPUT"; fi

      - name: Cache npm (modules + cache)
        if: steps.pkg.outputs.found == 'true'
        uses:  actions/checkout@v5
        with:
          path: |
            ~/.npm
            pr/node_modules
            pr/.eslintcache
          key: npm-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('pr/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-node${{ matrix.node }}-

      - name: Install deps & run ESLint
        if: steps.pkg.outputs.found == 'true'
        working-directory: pr
        shell: bash
        run: |
          set -euo pipefail
          node -v
          npm -v
          if [ -f package-lock.json ]; then
            npm ci --ignore-scripts --no-audit --fund=false
          else
            npm install --ignore-scripts --no-audit --fund=false
          fi
          files="$(git ls-files '*.js' '*.jsx' '*.mjs' '*.cjs' '*.ts' '*.tsx' || true)"
          if [ -z "$files" ]; then
            echo "No JS/TS files found."
            exit 0
          fi
          if [ -x ./node_modules/.bin/eslint ]; then
            printf '%s\n' $files | xargs -n50 ./node_modules/.bin/eslint -q --cache --cache-location .eslintcache
          else
            echo "ESLint not found in project (./node_modules/.bin/eslint). Skipping."
          fi

      - name: Skip ESLint (no package.json)
        if: steps.pkg.outputs.found != 'true'
        run: echo "No package.json found. Skipping ESLint."
