jobs:
  phpcs:
    name: PHP Coding Standards (no actions)
    if: >-
      (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
      && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2']
    steps:
      - name: Checkout PR code (merge ref)
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -euxo pipefail
          mkdir -p pr
          cd pr
          git init
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          if ! git fetch --no-tags --depth=1 origin "refs/pull/${{ github.event.pull_request.number }}/merge"; then
            git fetch --no-tags --depth=1 origin "refs/pull/${{ github.event.pull_request.number }}/head"
          fi
          git checkout -qf FETCH_HEAD
          git config --global --add safe.directory "$PWD"

      - name: Install PHP ${{ matrix.php }} and extensions via APT
        run: |
          set -euxo pipefail
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends software-properties-common ca-certificates lsb-release apt-transport-https gnupg
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update -y
          v="${{ matrix.php }}"
          sudo apt-get install -y --no-install-recommends \
            "php${v}" "php${v}-xml" "php${v}-mbstring" "php${v}-curl" "php${v}-zip" unzip
          sudo update-alternatives --set php "/usr/bin/php${v}" || true
          php -v
          php -m

      - name: Install Composer
        run: |
          set -euxo pipefail
          EXPECTED_SIGNATURE="$(curl -fsSL https://composer.github.io/installer.sig)"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
            echo 'ERROR: Invalid Composer installer signature' >&2
            exit 1
          fi
          sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer --quiet
          rm composer-setup.php
          composer --version

      - name: Install PHP dependencies
        working-directory: pr
        run: |
          if [ -f composer.json ]; then
            COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --no-progress --prefer-dist
          else
            echo "No composer.json found. Skipping."
          fi

      - name: Run PHPCS
        working-directory: pr
        run: |
          if [ -x vendor/bin/phpcs ]; then
            vendor/bin/phpcs -q
          else
            echo "PHPCS not found. Running php -l as fallback."
            git ls-files '*.php' | xargs -n1 -P4 php -l
          fi
